<<<<<<< Updated upstream
name: Verify AWS Authentication

on:
  push:
    branches:
      - main

jobs:
  verify-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Verify AWS Authentication
        run: |
          echo "Verifying AWS Authentication..."
          aws sts get-caller-identity
          aws s3 ls
          echo "Successfully authenticated with AWS!"
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
=======
name: Verify AWS Authentication

on:
  push:
    branches:
      - main

jobs:
  verify-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Verify AWS Authentication
        run: |
          echo "Verifying AWS Authentication..."
          aws sts get-caller-identity
          aws s3 ls
          echo "Successfully authenticated with AWS!"
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
>>>>>>> Stashed changes
